version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: ls
       - run: cd wp-content/themes/mondaytheme
       - run: ls
       - run: npm install
       - run: node deploy_app.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master