version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install --prefix ./wp-content/themes/mondaytheme/
       - run: node wp-content/themes/mondaytheme/deploy_app.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master